before:
  hooks:
  - go mod tidy

builds:
- env:
  - CGO_ENABLED=0
  - GO386=softfloat
  goos:
  - linux
  - windows
  - darwin
  ignore:
  - goos: darwin
    goarch: 386
  main: .
  ldflags:
  - -s -w -X github.com/zhilyaev/{{.ProjectName}}/Version={{.Version}}

archives:
- format_overrides:
  - goos: windows
    format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

release:
  name_template: "v{{.Version}}"
  #  draft: true
  prerelease: auto

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^WIP:'
    - Merge pull request
    - Merge branch
    - go mod tidy


dockers:
- dockerfile: Dockerfile
  image_templates:
  - "ghcr.io/zhilyaev/{{.ProjectName}}:{{ .Version }}"
  - "ghcr.io/zhilyaev/{{.ProjectName}}:latest"

  - "diamon/{{.ProjectName}}:{{ .Version }}"
  - "diamon/{{.ProjectName}}:latest"
  build_flag_templates:
  - "--pull"
  - "--label=org.opencontainers.image.created={{.Date}}"
  - "--label=org.opencontainers.image.title={{.ProjectName}}"
  - "--label=org.opencontainers.image.revision={{.FullCommit}}"
  - "--label=org.opencontainers.image.version={{.Version}}"
  - "--label=org.opencontainers.image.licenses=MIT"

  - "--platform=linux/amd64"
  - "--target=goreleaser"
  goos: linux
  goarch: amd64
  use: buildx
